version: '3.7'
services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - monitoring
    command: [
      "--jetstream",
      "--store_dir=/data",
      "-m", "8222"  # This enables the monitoring endpoint on port 8222
    ]
    volumes:
      - nats_data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - C:\Users\luis.amicucci\Documents\Projects\MessageQueueProvider\prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nats

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  nats_data:

networks:
  monitoring:
    driver: bridge
